import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header/HeaderComponent";
import {Provider} from "react-redux";
import {ThemeSwitcher} from "@/components/Header/ThemeSwitcher/ThemeSwitcher";
import {store} from "@/redux/store";
import {Providers} from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'The Movies',
  description: "Generated by create next app",
};
type PropType={
  children: React.ReactNode;
}
export default function RootLayout({
  children,
}: Readonly<PropType>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Providers>
      <HeaderComponent/>
      {children}
      </Providers>
      </body>

    </html>
  );
}
