import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header/HeaderComponent";
import {Providers} from "@/provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'The Movies',
  description: "Generated by create next app",
};
type PropType={
  children: React.ReactNode;
}
export default function RootLayout({
  children,
}: Readonly<PropType>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Providers>
      <HeaderComponent/>
      {children}
      </Providers>
      </body>

    </html>
  );
}
